Error at line 4: 
def fatorial(int n) : int {
inválido na gramática
Error at line 7: 
def fatorial(int n) : int {
inválido na gramática
Error at line 7: 
def fatorial(int n) : int {
literal errado
Error at line 7: 
def fatorial(int n) : int {
; esperado
Error at line 7: 
def fatorial(int n) : int {
literal errado
Error at line 7: 
def fatorial(int n) : int {
; esperado
Error at line 7: 
def fatorial(int n) : int {
} esperado
Error at line 7: 
def fatorial(int n) : int {
def esperado
Error at line 7: 
def fatorial(int n) : int {
def esperado
Error at line 7: 
def fatorial(int n) : int {
def esperado
Error at line 7: 
def fatorial(int n) : int {
def esperado
Error at line 7: 
def fatorial(int n) : int {
def esperado
Error at line 8: 
def fatorial(int n) : int {
def esperado
Error at line 8: 
def fatorial(int n) : int {
def esperado
Error at line 9: 
def fatorial(int n) : int {
def esperado
Error at line 10: 
def fatorial(int n) : int {
def esperado
Error at line 10: 
def fatorial(int n) : int {
def esperado
Error at line 10: 
def fatorial(int n) : int {
def esperado
Error at line 11: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 12: 
def fatorial(int n) : int {
def esperado
Error at line 13: 
def fatorial(int n) : int {
def esperado
Error at line 14: 
def fatorial(int n) : int {
def esperado
Error at line 18: 
def fatorial(int n) : int {
literal errado
Error at line 18: 
def fatorial(int n) : int {
; esperado
Error at line 18: 
def fatorial(int n) : int {
} esperado
Error at line 18: 
def fatorial(int n) : int {
def esperado
Error at line 19: 
def fatorial(int n) : int {
def esperado
Error at line 19: 
def fatorial(int n) : int {
def esperado
Error at line 19: 
def fatorial(int n) : int {
def esperado
Error at line 19: 
def fatorial(int n) : int {
def esperado
Error at line 19: 
def fatorial(int n) : int {
def esperado
Error at line 20: 
def fatorial(int n) : int {
def esperado
Error at line 20: 
def fatorial(int n) : int {
def esperado
Error at line 20: 
def fatorial(int n) : int {
def esperado
Error at line 20: 
def fatorial(int n) : int {
def esperado
Error at line 20: 
def fatorial(int n) : int {
def esperado
Error at line 21: 
def fatorial(int n) : int {
def esperado
Error at line 21: 
def fatorial(int n) : int {
def esperado
Error at line 21: 
def fatorial(int n) : int {
def esperado
Error at line 21: 
def fatorial(int n) : int {
def esperado
Error at line 21: 
def fatorial(int n) : int {
def esperado
Error at line 21: 
def fatorial(int n) : int {
def esperado
Error at line 22: 
def fatorial(int n) : int {
def esperado
Error at line 23: 
def fatorial(int n) : int {
def esperado
Error at line 23: 
def fatorial(int n) : int {
def esperado
Error at line 23: 
def fatorial(int n) : int {
def esperado
Error at line 23: 
def fatorial(int n) : int {
def esperado
Error at line 23: 
def fatorial(int n) : int {
def esperado
Error at line 24: 
def fatorial(int n) : int {
def esperado
Error at line 24: 
def fatorial(int n) : int {
def esperado
Error at line 24: 
def fatorial(int n) : int {
def esperado
Error at line 24: 
def fatorial(int n) : int {
def esperado
Error at line 24: 
def fatorial(int n) : int {
def esperado
Error at line 25: 
def fatorial(int n) : int {
def esperado
Error at line 25: 
def fatorial(int n) : int {
def esperado
Error at line 25: 
def fatorial(int n) : int {
def esperado
Error at line 25: 
def fatorial(int n) : int {
def esperado
Error at line 25: 
def fatorial(int n) : int {
def esperado
Error at line 26: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
) faltando
Error at line 29: 
def fatorial(int n) : int {
; esperado
Error at line 29: 
def fatorial(int n) : int {
} esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 29: 
def fatorial(int n) : int {
def esperado
Error at line 30: 
def fatorial(int n) : int {
def esperado
